name: Deploy To PROD

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.0
#
permissions:
  id-token: write
  contents: read

jobs:
  deploy_fpm:
    environment: PROD
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
