name: Deploy To Dev

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Who to greet
        options:
          - all
          - fpm
          - worker
          - cron
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy_fpm:
    environment: DEV
    if: ${{ github.event.inputs.service == 'all' || github.event.inputs.service == 'fpm'}}
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: echo outputs
        env:
          TEST_DEV_SECRET: ${{ secrets.TEST_DEV_SECRET }}
          ACTIONS_SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          echo ${{ github.event.inputs.service }}
          echo ${TEST_DEV_SECRET}
          echo ${ACTIONS_SECRET}

  deploy_cron:
    if: ${{ github.event.inputs.service == 'all' || github.event.inputs.service == 'cron'}}
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: echo outputs
        run: |
          echo ${{ github.event.inputs.service }}
