name: Deploy To Dev

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Who to greet
        options:
          - all
          - fpm
          - worker
          - cron
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy_fpm:
    environment: DEV
    if: ${{ github.event.inputs.service == 'all' || github.event.inputs.service == 'fpm'}}
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
#
#      - name: echo outputs
#        env:
#          TEST_DEV_SECRET: ${{ secrets.TEST_DEV_SECRET }}
#          ACTIONS_SECRET: ${{ secrets.ACTIONS_SECRET }}
#          SOME_VARIABLE: ${{ vars.SOME_VARIABLE }}
#          DEV_VAR: ${{ vars.DEV_VAR }}
#        run: |
#          echo ${{ github.event.inputs.service }}
#          echo ${TEST_DEV_SECRET}
#          echo ${ACTIONS_SECRET}
#          echo ${SOME_VARIABLE}
#          echo ${DEV_VAR}

      - name: new tag
        id: new-tag
        env:
          TAG: ${{ github.event.inputs.service }}
        run: echo "IMAGE_TAG=${TAG##*or}"

      - name: echo tag
        id: echo-tag
        env:
          TAG: ${{ github.event.inputs.service }}
        run: echo -n "::set-output name=tag::${TAG##*or}"

      - name: Test variable
        run: |
          echo "old tag ${{ steps.echo-tag.outputs.tag }}"
          echo "The selected color is ${{ steps.new-tag.outputs.IMAGE_TAG }}"


  deploy_cron:
    if: ${{ github.event.inputs.service == 'all' || github.event.inputs.service == 'cron'}}
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: echo outputs
        run: |
          echo ${{ github.event.inputs.service }}
