name: Release Drafter
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-draft-template.yml
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
